version: "3.3"
services:
  db:
    image: mysql:8.0.2
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-container
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: ponto_inteligente
    volumes:
      - ./api/db/data:/var/lib/mysql
    ports:
      - "3306:3306"